### ISSUE TITLE
Adicionar o idioma holandês ('nl') à lista de possíveis idiomas

### ISSUE THREAD

**Issue by Caboverde** [scieloorg/export-sci#28]
Olá Fabio, pelo relatório de erros da coleção da Africa, à qual tive acesso, muitos se referem ao idioma 'nl', bastante presente na coleção.
Sugiro adicionar à lista na *XSD*
(https://github.com/scieloorg/export-sci/blob/master/xsd/ThomsonReuters_publishing.xsd).
Obrigado!
Alvaro

**Comment by scielo** [comment]
Olá Alvaro,

A mudança do Schema depende de alguns processos demorados feitos pela
Thomson. Já solicitamos que o Schema contemple a lista ISO 639-1 essa
mudança só será incorporada em um próximo release do SciELO CI.

Por hora vamos contornar esse problema de outra maneira.

Em breve será enviada uma nova lista de erros, e provavelmente estes casos
não estarão presentes.

Att,

*Fabio Batalha C. Santos*
Colegiado SciELO
www.scielo.org
FAPESP - CNPq - BIREME - FapUNIFESP

2015-11-11 18:29 GMT-02:00 Caboverde Tecnologia e Serviços <
notifications@github.com>:
